nodeLinker: node-modules

packageExtensions:
  '@remix-run/dev@*':
    peerDependencies:
      react: '*'
      react-dom: '*'
  '@remix-run/cloudflare-workers@*':
    peerDependencies:
      react: '*'
      react-dom: '*'
  'eslint-config-airbnb-typescript@*':
    peerDependencies:
      eslint: '*'
      eslint-plugin-import: '*'

yarnPath: .yarn/releases/yarn-3.2.0.cjs
