name = "tweetscape"
type = "javascript"

zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2022-02-24"

[site]
bucket = "./public"
entry-point = "."

[build]
command = "yarn build"

[build.upload]
format="service-worker"

[miniflare]
env_path=".env"

# [secrets]
# COOKIE_SECRET
