name = "tweetscape"
type = "javascript"

zone_id = "5dfe3e061765ec5eab837b2e438f75df"
account_id = "52f1256865b2f45d0ad43de3bf56fea2"
route = "https://tweetscape.co/*"
compatibility_date = "2022-02-24"

[site]
bucket = "./public"
entry-point = "."

[build]
command = "yarn build"

[build.upload]
format="service-worker"

[miniflare]
env_path=".env"

# [secrets]
# COOKIE_SECRET
