name: Build

on:
  push:

env:
  NODE_ENV: test
  COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
            ~/.cache/yarn
            .next/cache
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - run: yarn install --immutable
      - run: yarn build
