name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
            ~/.cache/yarn
            .next/cache
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - run: yarn install --immutable
      - run: yarn build
        env:
          NODE_ENV: test
          COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - uses: superfly/flyctl-actions@master
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        with:
          args: 'proxy 5432 -a tweetscape-db'
      - run: yarn start & yarn wait-on http-get://localhost:3000
        env:
          NODE_ENV: test
          COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - run: yarn start:cy --record --parallel --headless --group firefox -b firefox
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      - uses: codecov/codecov-action@v1
        if: ${{ success() || failure() }}
